[10.0] add flag to automatically assign computed value of level_id
acsone/product-attribute pull request #3
Opened 2022-01-21 08:43 UTC by lmarion-source

2022-01-25 07:12 UTC, lmignon commented on product_abc_classification_sale_stock/models/__init__.py
> +from . import abc_sale_stock_level_history
@lmarion-source ici il y a un problème pep8.. pas de newline à la fin du fichier

2022-01-25 07:14 UTC, lmignon commented on product_abc_classification_sale_stock/tests/test_abc_classification_product_level.py
> +        super(TestABCClassificationProductLevel, cls).setUpClass()
Ces lignes ne sont pas nécessarires puisqu'aucun code n'est ajouté à la méthode

2022-01-25 07:15 UTC, lmignon commented on product_abc_classification_sale_stock/tests/test_abc_classification_profile.py
>      @classmethod
idem ici, méthode à supprimer

2022-01-25 07:19 UTC, lmignon requested changes

2022-01-25 07:19 UTC, lmignon commented on product_abc_classification_sale_stock/tests/test_abc_classification_profile.py
> +        self.assertEqual(self.product1.abc_classification_product_level_ids.manual_level_id, self.level_A)
@lmarion-source Ce test n'est-il pas un doublon de TestABCClassificationProductLevel.? De plus pq avoir créer un classe de test supplémentaire `TestABCClassificationProductLevel? Qu'apporte-t-elle par rapport à la classe existante? LE fait d'avoir une classe supplémentaire, double le temps des tests car le setupClass est exécuté 2 fois...

2022-01-25 12:32 UTC, lmignon approved these changes

2022-01-25 12:41 UTC, lmignon requested changes

2022-01-25 12:41 UTC, lmignon commented on product_abc_classification_sale_stock/models/abc_classification_profile.py
> +            res.update({"manual_level_id": sale_stock_data.computed_level.id})
@lmarion-source En fait, ce n'est pas bon de le faire ici. Tu déclare un champ dans classification_base pour uniquement l'utiliser ici.... En fait tu dois surcharger le write dans 'product_abc_classification_base/models/ abc_classification_product_level' et tenir compte du profil pour ajouter "manual_level_id" dans vals.... le tout par profil. Comme cela tout devient générique.

2022-01-26 07:52 UTC, lmignon requested changes

2022-01-26 07:52 UTC, lmignon commented on product_abc_classification_base/models/abc_classification_product_level.py
> +                vals["manual_level_id"] = vals["computed_level_id"]
@lmarion-source Cela ne peut pas fonctionner.... Tu modifies à chaque fois le même dictionnaire...
Il faut traiter les cas suivants:
* "profile_id" est aussi dans vals
* self concerne des records dans différents profiles et tous ne sont pas déclaré avec auto_apply_computed_value
*

2022-01-26 07:53 UTC, lmignon commented
et je ne comprends pas comment on a maintenant un conflit qui n'existait pas avant...

2022-01-26 17:54 UTC, sbidoul commented on product_abc_classification_base/models/abc_classification_product_level.py
> +                vals["manual_level_id"] = vals["computed_level_id"]
Je ne sais pas pourquoi GitHub a décidé de m'envoyer des notif pour ceci...

Mais, je vois un `vals["..."] = ...`, et j'en profite pour rappeler qu'il ne faut jamais jamais jamis modifier le dictionnaire vals d'un write ou create. En effet, ces opérations write/create sont susceptibles d'être réessayées plusieurs fois par Odoo en cas de deadlock sur la base de données. Et si on a modifié vals, il réessaie donc avec des paramètres différents. C'est le genre de bugs hyper difficile à comprendre quand ça se produit en prod.

2022-01-27 12:57 UTC, lmignon requested changes

2022-01-27 12:57 UTC, lmignon commented on product_abc_classification_base/models/abc_classification_product_level.py
> +            vals["manual_level_id"] = vals["computed_level_id"]
@lmarion-source euhhhhhhh 
Cette clef n'est pas un champ du modèle. Elle ne peut donc pas être ajoutée dans vals. Dans le cas d'un create tu dois avoir profiles_id dans vals. Et c'est à partir de là que tu sais si il y a auto_apply_computed_value

2022-01-27 14:49 UTC, lmignon approved these changes

2022-01-27 14:49 UTC, lmignon commented on product_abc_classification_base/models/abc_classification_product_level.py
> +            vals["manual_level_id"] = vals["computed_level_id"]
@lmarion-source Attention, au moment du call à create, les containtes ne sont pas vérifiées donc "profile_id" pourrait ne pas être dans vals.... Dans un tel cas, le code va échoué avant que le système ait pu répondre avec un message approprié pour la valeur manquante...
```suggestion
        if "profile_id" in vals:
            profile = self.env["abc.classification.profile"].browse(vals['profile_id'])
            if profile.auto_apply_computed_value and "computed_level_id" in vals:
                vals["manual_level_id"] = vals["computed_level_id"]
```

2022-01-27 14:49 UTC, lmignon commented on product_abc_classification_base/models/abc_classification_product_level.py
> +            vals["manual_level_id"] = vals["computed_level_id"]
@lmarion-source je vais finir la PR

2022-01-27 15:07 UTC, merged